"""Pure renderer for the one ordinary GitHub workflow owned by init."""

from __future__ import annotations

import re

from skillroll.release import exact_action_ref, release_metadata

DEFAULT_ACTION_REF = exact_action_ref(release_metadata())
_ACTION_REF = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+@[A-Za-z0-9_.-]+$")


def valid_action_ref(value: str) -> bool:
    """Accept a compact literal Action reference, never a shell expression."""
    return bool(_ACTION_REF.fullmatch(value))


def render_workflow(action_ref: str, api_key_env: str | None) -> bytes:
    """Render visible GitHub policy; only live jobs receive a static secret."""
    key = "SKILLROLL_API_KEY" if api_key_env is None else api_key_env
    secret = f"          {key}: ${{{{ secrets.{key} }}}}\n"
    return f"""# Generated by skillroll init --github-workflow. Review before enabling.
name: SkillRoll

on:
  pull_request:
  workflow_dispatch:
    inputs:
      reviewed_ref:
        description: Exact reviewed commit SHA or refs/pull/NUMBER/head
        required: true
        type: string
      scope:
        description: What to evaluate
        required: true
        default: all
        type: choice
        options: [all, skill, case]
      selection_path:
        description: Skill or eval-case path for the selected scope
        required: false
        type: string
      samples:
        description: Independent model-backed samples to run (1-10)
        required: false
        default: 1
        type: string
      with_skill_control:
        description: Also run samples without the selected skill for comparison
        required: false
        default: false
        type: boolean
      run_repository_checks:
        description: Run repository-declared commands in a separate secretless job
        required: true
        default: false
        type: boolean
  release:
    types: [published]

permissions:
  contents: read

concurrency:
  group: >-
    skillroll-${{{{ github.workflow }}}}-${{{{ github.event.pull_request.number ||
    inputs.reviewed_ref || github.ref }}}}
  cancel-in-progress: ${{{{ github.event_name == 'pull_request' }}}}

jobs:
  validate:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{{{ github.event.pull_request.head.sha }}}}
          fetch-depth: 0
          persist-credentials: false
      - id: validate
        uses: {action_ref}
        continue-on-error: true
        with:
          mode: validate
          scope: changed
          base-sha: ${{{{ github.event.pull_request.base.sha }}}}
          head-sha: ${{{{ github.event.pull_request.head.sha }}}}
          # Repository-declared commands are arbitrary code. They are not run
          # automatically for pull requests, including fork pull requests.
          run-commands: false
          command-notice: true
          fork-notice: ${{{{ github.event.pull_request.head.repo.fork }}}}
      - name: Fail when repository validation is unsafe or broken
        if: >-
          always() &&
          steps.validate.outputs.outcome != 'PASS' &&
          steps.validate.outputs.outcome != 'INCOMPLETE'
        run: exit 1

  live-eval:
    if: >-
      vars.SKILLROLL_LIVE_EVAL == 'true' &&
      github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      github.event.pull_request.author_association == 'OWNER'
    needs: validate
    runs-on: ubuntu-latest
    environment: skillroll-eval
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{{{ github.event.pull_request.head.sha }}}}
          fetch-depth: 0
          persist-credentials: false
      - id: live
        uses: {action_ref}
        continue-on-error: true
        env:
{secret}        with:
          mode: eval
          scope: changed
          base-sha: ${{{{ github.event.pull_request.base.sha }}}}
          head-sha: ${{{{ github.event.pull_request.head.sha }}}}
          samples: 1
          with-skill-control: false
          run-commands: false
          command-notice: true
          upload-artifact: true
      - name: Fail when live evaluation fails
        if: >-
          always() &&
          steps.live.outputs.outcome != 'PASS' &&
          steps.live.outputs.outcome != 'INCOMPLETE'
        run: exit 1

  trusted-live-eval:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: skillroll-eval
    steps:
      - name: Check the reviewed revision format
        uses: {action_ref}
        with:
          mode: validate-ref
          scope: all
          reviewed-ref: ${{{{ inputs.reviewed_ref }}}}
      - name: Explain the trusted run
        run: >-
          echo 'This run evaluates the reviewed revision you entered without
          running repository-declared commands. Enable the separate
          trusted-checks job only after reviewing that exact revision.'
      - uses: actions/checkout@v7
        with:
          ref: ${{{{ inputs.reviewed_ref }}}}
          fetch-depth: 0
          persist-credentials: false
      - uses: {action_ref}
        env:
{secret}        with:
          mode: eval
          scope: ${{{{ inputs.scope }}}}
          selection-path: ${{{{ inputs.selection_path }}}}
          samples: ${{{{ inputs.samples }}}}
          with-skill-control: ${{{{ inputs.with_skill_control }}}}
          run-commands: false
          command-notice: true
          upload-artifact: true

  trusted-checks:
    if: github.event_name == 'workflow_dispatch' && inputs.run_repository_checks
    runs-on: ubuntu-latest
    steps:
      - name: Check the reviewed revision format
        uses: {action_ref}
        with:
          mode: validate-ref
          scope: all
          reviewed-ref: ${{{{ inputs.reviewed_ref }}}}
      - name: Explain the repository-check trust boundary
        run: >-
          echo 'This separate secretless job runs repository-declared commands
          from the reviewed revision. They may change the disposable runner or
          use its network. Continue only after you have reviewed that exact
          revision.'
      - uses: actions/checkout@v7
        with:
          ref: ${{{{ inputs.reviewed_ref }}}}
          fetch-depth: 0
          persist-credentials: false
      - uses: {action_ref}
        with:
          mode: validate
          scope: ${{{{ inputs.scope }}}}
          selection-path: ${{{{ inputs.selection_path }}}}
          run-commands: true

  release-verify:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{{{ github.event.release.tag_name }}}}
          fetch-depth: 0
          persist-credentials: false
      - id: release
        uses: {action_ref}
        continue-on-error: true
        with:
          mode: validate
          scope: all
          run-commands: false
          command-notice: true
      - name: Fail when release validation is unsafe or broken
        if: >-
          always() &&
          steps.release.outputs.outcome != 'PASS' &&
          steps.release.outputs.outcome != 'INCOMPLETE'
        run: exit 1
""".encode()
